############################################################################### 
# Authors:  Pablo Arancibia 
# Date:     dic 2020
# Licence:  MIT
# Project:  DAM - CEIoT - Project TP Final
# Brief:    Docker compose file to configure whole application
#
# How to use the containers
#   - docker exec -it container_name /bin/sh
#
###############################################################################

version: '3'

services:

    mysql-server:
        image:                      mysql:5.7
        
        hostname:                   mysql-server
        container_name:             mysql-server
        environment:
            MYSQL_ROOT_PASSWORD:    userpass
        ports:
            -                       "3307:3306"
        volumes:
            -                       ./db/dumps:/docker-entrypoint-initdb.d
            -                       ./db/data:/var/lib/mysql
        networks:
            -                       dam-ceiot-network

    mysql-admin:
        image:                      phpmyadmin/phpmyadmin
        hostname:                   mysql-admin
        container_name:             mysql-admin
        environment: 
            PMA_HOST:               mysql-server
            PMA_PORT:               3307
            MYSQL_ROOT_PASSWORD:    userpass
        networks:
            -                       dam-ceiot-network
        depends_on:
            -                       mysql-server
        ports:
            -                       "8001:80"

    
networks:
    dam-ceiot-network:
        driver:                     bridge